import tkinter as tk

root = tk.Tk()
b1 = tk.Button(root, text="arrow", cursor="arrow").pack()
b2 = tk.Button(root, text="circle", cursor="circle").pack()
b3 = tk.Button(root, text="clock", cursor="clock").pack()
b4 = tk.Button(root, text="cross", cursor="cross").pack()
b5 = tk.Button(root, text="dotbox", cursor="dotbox").pack()
b6 = tk.Button(root, text="exchange", cursor="exchange").pack()
b7 = tk.Button(root, text="fleur", cursor="fleur").pack()
b8 = tk.Button(root, text="heart", cursor="heart").pack()
b9 = tk.Button(root, text="man", cursor="man").pack()
b10 = tk.Button(root, text="mouse", cursor="mouse").pack()
b11 = tk.Button(root, text="pirate", cursor="pirate").pack()
b12 = tk.Button(root, text="plus", cursor="plus").pack()
b13 = tk.Button(root, text="question_arrow", cursor="question_arrow").pack()
b14 = tk.Button(root, text="shuttle", cursor="shuttle").pack()
b15 = tk.Button(root, text="sizing", cursor="sizing").pack()
b16 = tk.Button(root, text="spider", cursor="spider").pack()
b17 = tk.Button(root, text="spraycan", cursor="spraycan").pack()
b18 = tk.Button(root, text="star", cursor="star").pack()
b19 = tk.Button(root, text="target", cursor="target").pack()
b20 = tk.Button(root, text="tcross", cursor="tcross").pack()
b21 = tk.Button(root, text="umbrella", cursor="umbrella").pack()
b22 = tk.Button(root, text="watch", cursor="watch").pack()
b23 = tk.Button(root, text="bottom_side", cursor="bottom_side").pack()
b24 = tk.Button(root, text="bottom_left_corner", cursor="bottom_left_corner").pack()
b25 = tk.Button(root, text="bottom_right_corner", cursor="bottom_right_corner").pack()
b26 = tk.Button(root, text="left_side", cursor="left_side").pack()
b27 = tk.Button(root, text="right_side", cursor="right_side").pack()
b28 = tk.Button(root, text="top_side", cursor="top_side").pack()
b29 = tk.Button(root, text="top_left_corner", cursor="top_left_corner").pack()
b30 = tk.Button(root, text="top_right_corner", cursor="top_right_corner").pack()